[metadata]
name = pqca
version = 3.0.0-alpha1
author = Hector Miller-Bakewell
author_email = hmillerbakewell@gmail.com
description = Construct and simulate partitioned quantum cellular automata
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = https://github.com/hmillerbakewell/partitioned-quantum-cellular-automata
keywords = quantum computing, cellular automata
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10

install_requires =
    qiskit>=2.1.0
    qiskit_ibm_runtime>=0.45
    qiskit_aer>=0.17.2
test_requires =
    pytest

[options.packages.find]
where = src

